version: '3.8'

services:
  server:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - '8000:8000'
    environment:
      - FLASK_ENV=development
      - FLASK_APP=src/app.py
    command: python -m flask run --host=0.0.0.0 --port=8000

  test:
    build: .
    volumes:
      - .:/usr/src/app
    command: /bin/bash -c "pip install -r requirements-test.txt && pytest test/"
    depends_on:
      - server

